version: 2
archives:
  - name_template: >-
      {{ .ProjectName }}_ {{- title .Os }}_ {{- if eq .Arch "amd64" }}x86_64 {{- else if eq .Arch "386" }}i386 {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: ["zip"]
    files:
      - README.md
      - LICENSE
      - completions/*
      - manpages/*
before:
  hooks:
    - go mod tidy
    - go mod download
    - ./scripts/completions.sh
    - ./scripts/manpages.sh
builds:
  - id: tf-plan-summary
    main: ./main.go
    binary: tf-plan-summary
    ldflags:
      - -w -s
      - -X "github.com/tf-plan-summary/tf-plan-summary/pkg/core/version.BuildTime={{.Date}}"
      - -X "github.com/tf-plan-summary/tf-plan-summary/pkg/core/version.GoVersion={{.Env.GOVERSION}}"
      - -X "github.com/tf-plan-summary/tf-plan-summary/pkg/core/version.Version={{ .Version }}"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
changelog:
  ## Delegate Changelog to release-drafter
  disable: true
checksum:
  name_template: "checksums.txt"
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
nfpms:
  - file_name_template: "{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    homepage: "https://lois.postu.la/tf-plan-summary"
    description: "Terragrunt-Plan-Summary is a tool to summarize terragrunt parallel terragrunt plans."
    maintainer: "Loïs Postula <lois@postu.la>"
    license: "Apache-2.0"
    vendor: Terragrunt-Plan-Summary
    section: utils
    formats:
      - apk
      - deb
      - rpm
    dependencies:
      - ca-certificates
    contents:
      - src: ./completions/tf-plan-summary.bash
        dst: /usr/share/bash-completion/completions/tf-plan-summary
        file_info:
          mode: 0644
      - src: ./completions/tf-plan-summary.fish
        dst: /usr/share/fish/vendor_completions.d/tf-plan-summary.fish
        file_info:
          mode: 0644
      - src: ./completions/tf-plan-summary.zsh
        dst: /usr/share/zsh/vendor-completions/_tf-plan-summary
        file_info:
          mode: 0644
      - src: ./manpages/tf-plan-summary.1.gz
        dst: /usr/share/man/man1/tf-plan-summary.1.gz
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/tf-plan-summary/copyright
        file_info:
          mode: 0644
snapshot:
  version_template: "{{ .Tag }}-next"
sboms:
  - artifacts: archive
signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    signature: "${artifact}.sig"
    output: true
    artifacts: checksum
    args:
      - sign-blob
      - "--yes"
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
