version: 2
archives:
  - name_template: >-
      {{ .ProjectName }}_ {{- title .Os }}_ {{- if eq .Arch "amd64" }}x86_64 {{- else if eq .Arch "386" }}i386 {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: ["zip"]
    files:
      - README.adoc
      - LICENSE
      - completions/*
      - manpages/*
before:
  hooks:
    - go mod tidy
    - go mod download
    - ./scripts/completions.sh
    - ./scripts/manpages.sh
builds:
  - id: terragrunt-plan-summary
    main: ./main.go
    binary: terragrunt-plan-summary
    ldflags:
      - -w -s
      - -X "github.com/loispostula/terragrunt-plan-summary/pkg/core/version.BuildTime={{.Date}}"
      - -X "github.com/loispostula/terragrunt-plan-summary/pkg/core/version.GoVersion={{.Env.GOVERSION}}"
      - -X "github.com/loispostula/terragrunt-plan-summary/pkg/core/version.Version={{ .Version }}"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
changelog:
  ## Delegate Changelog to release-drafter
  disable: true
checksum:
  name_template: 'checksums.txt'
dockers:
  - image_templates:
      - 'terragrunt-plan-summary/terragrunt-plan-summary:{{ .Tag }}-amd64'
      - 'ghcr.io/terragrunt-plan-summary/terragrunt-plan-summary:{{ .Tag }}-amd64'
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--no-cache"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
    goos: linux
    goarch: amd64
    extra_files:
      - Makefile
  - image_templates:
      - 'terragrunt-plan-summary/terragrunt-plan-summary:{{ .Tag }}-arm64'
      - 'ghcr.io/terragrunt-plan-summary/terragrunt-plan-summary:{{ .Tag }}-arm64'
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--no-cache"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
    goos: linux
    goarch: arm64
    extra_files:
      - Makefile
docker_signs:
  - cmd: cosign
    artifacts: manifests
    output: true
    args:
      - 'sign'
      - '--yes'
      - '${artifact}@${digest}'
docker_manifests:
  - name_template: 'terragrunt-plan-summary/terragrunt-plan-summary:{{ .Tag }}'
    image_templates:
      - 'terragrunt-plan-summary/terragrunt-plan-summary:{{ .Tag }}-amd64'
      - 'terragrunt-plan-summary/terragrunt-plan-summary:{{ .Tag }}-arm64'
  - name_template: 'ghcr.io/terragrunt-plan-summary/terragrunt-plan-summary:{{ .Tag }}'
    image_templates:
      - 'ghcr.io/terragrunt-plan-summary/terragrunt-plan-summary:{{ .Tag }}-amd64'
      - 'ghcr.io/terragrunt-plan-summary/terragrunt-plan-summary:{{ .Tag }}-arm64'
  - name_template: 'terragrunt-plan-summary/terragrunt-plan-summary:latest'
    image_templates:
      - 'terragrunt-plan-summary/terragrunt-plan-summary:{{ .Tag }}-amd64'
      - 'terragrunt-plan-summary/terragrunt-plan-summary:{{ .Tag }}-arm64'
  - name_template: 'ghcr.io/terragrunt-plan-summary/terragrunt-plan-summary:latest'
    image_templates:
      - 'ghcr.io/terragrunt-plan-summary/terragrunt-plan-summary:{{ .Tag }}-amd64'
      - 'ghcr.io/terragrunt-plan-summary/terragrunt-plan-summary:{{ .Tag }}-arm64'
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage: 'https://www.terragrunt-plan-summary.io'
    description: 'Terragrunt-Plan-Summary is a declarative dependency management command line tool.'
    maintainer: 'Olivier Vernin <olivier@vernin.me>'
    license: 'Apache-2.0'
    vendor: Terragrunt-Plan-Summary
    section: utils
    formats:
      - apk
      - deb
      - rpm
    dependencies:
      - ca-certificates
    contents:
      - src: ./completions/terragrunt-plan-summary.bash
        dst: /usr/share/bash-completion/completions/terragrunt-plan-summary
        file_info:
          mode: 0644
      - src: ./completions/terragrunt-plan-summary.fish
        dst: /usr/share/fish/vendor_completions.d/terragrunt-plan-summary.fish
        file_info:
          mode: 0644
      - src: ./completions/terragrunt-plan-summary.zsh
        dst: /usr/share/zsh/vendor-completions/_terragrunt-plan-summary
        file_info:
          mode: 0644
      - src: ./manpages/terragrunt-plan-summary.1.gz
        dst: /usr/share/man/man1/terragrunt-plan-summary.1.gz
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/terragrunt-plan-summary/copyright
        file_info:
          mode: 0644
snapshot:
  version_template: "{{ .Tag }}-next"
sboms:
  - artifacts: archive
signs:
  - cmd: cosign
    certificate: '${artifact}.pem'
    signature: "${artifact}.sig"
    output: true
    artifacts: checksum
    args:
      - sign-blob
      - '--yes'
      - '--output-certificate=${certificate}'
      - '--output-signature=${signature}'
      - '${artifact}'
