changelogs:
  - kind: github
    dir: docs/src/changelogs
    formats:
      - extension: markdown
        # frontmatters: |
        #   ---
        #   title: "{{ .Changelog.Name }}"
        #   date: {{ .Changelog.PublishedAt }}
        #   ---
        filetemplate: |
          {{ .FrontMatters }}
          {{ if .Changelog.Author }}
          *{{ .Changelog.Author }} released this {{ .Changelog.PublishedAt }}*
          {{ end }}


          ## Description

          {{ if .Changelog.DescriptionHTML }}
          {{ .Changelog.DescriptionHTML }}
          {{ else if .Changelog.Description}}
          {{ .Changelog.Description }}
          {{ end}}

          {{ if .Changelog.Assets }}
          ## Download

          | Name | Created At | Updated At |
          |------|------------|------------|
          {{ range $asset := .Changelog.Assets -}}
          | [{{ $asset.Name }}]({{ $asset.DownloadURL }}) | {{ $asset.CreatedAt }} | {{ $asset.UpdatedAt }} |
          {{ end -}}
          {{ end}}

          {{ if .Changelog.URL }}
          *Information retrieved from [here]({{.Changelog.URL}})*
          {{ end}}
        indexfilename: "_SUMMARY"
        indexfiletemplate: |2
          {{ range $pos, $release := .Changelogs }}
            -  [{{ $release.Name}}](changelogs/changelogs/{{ $release.Tag }}.md) {{ if (eq $pos 0) }}(latest){{ end}}
          {{ end }}
        # indexfrontmatters: |
        #   # ---
        #   # title: "Index Changelog"
        #   # ---
    spec:
      owner: tf-plan-summary
      repository: tf-plan-summary
