[book]
authors = ["Loïs Postula"]
language = "en"
src = "src"
title = "tf-plan-summary"
description = "Summarize terraform plans"


[output.html]
smart-punctuation = true
mathjax-support = true
git-repository-url = "https://github.com/tf-plan-summary/tf-plan-summary/tree/main/docs"
edit-url-template = "https://github.com/tf-plan-summary/tf-plan-summary/edit/main/docs/{path}"
hash-files = true

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

