---
name: Publish Release Assets
on:
  workflow_dispatch: null
  release:
    types: [published]
permissions: {}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@f0fe604f8a612776892427721526b4c7cfb23aba # v31.4.1
      - uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: generate_homebrew_token
        with:
          app-id: ${{ secrets.LOIS_BOT_APP_ID }}
          private-key: ${{ secrets.LOIS_BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: |
            terragrunt-plan-summary
            homebrew-terragrunt-plan-summary
      - name: GoReleaser
        if: success()
        env:
          COSIGN_PWD: ${{ secrets.COSIGN_PWD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ steps.generate_homebrew_token.outputs.token }}
        run: |
          build.all
