name: updatecli
on:
  release: null
  workflow_dispatch: null
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Run every day
    - cron: "0 0 * * *"
permissions: {}
jobs:
  updatecli:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: "Checkout"
        uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683" # v4.2.2
      - name: "Setup updatecli"
        uses: "updatecli/updatecli-action@b2d27ae973914f05b36ac2e9fb56378fc9b62df0" # v2
      - uses: DeterminateSystems/flake-checker-action@0af51e37404acfb298f7e2eec77470be27eb57c5 # v10
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          use-flakehub: false
      - name: "Run updatecli in dryrun"
        run: "updatecli compose diff"
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: generate_token
        if: github.ref == 'refs/heads/main'
        with:
          app-id: ${{ secrets.LOIS_BOT_APP_ID }}
          private-key: ${{ secrets.LOIS_BOT_PRIVATE_KEY }}
      - name: "Run updatecli"
        if: github.ref == 'refs/heads/main'
        run: "updatecli compose apply"
        env:
          GITHUB_ACTOR: lois-bot
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
